### ISSUE TITLE
Can't run showPotentialCalendarEventsOfMonth 

### ISSUE THREAD

**Issue by rmenner** [t1k3hu/laravel-calendar-event#7]
I get this error `The separation symbol could not be found Unexpected data found.` Do you get any errors when running this @t1k3 ? Sorry I missed this with my initial test cases.

**Comment by rmenner** [comment]
Ok so I figured out that with certain event types if I don't add a end date it will fail.

**Comment by t1k3** [comment]
I will check it (on Sunday or Monday).

**Comment by t1k3** [comment]
@rmenner I found a bug - after merge date/time, I need more time to fix.

**Comment by t1k3** [comment]
@rmenner Please check it: https://github.com/t1k3/laravel-calendar-event/tree/fix/date-time-merge

**Comment by rmenner** [comment]
@t1k3 checking it now

**Comment by rmenner** [comment]
@t1k3 Only "bug" I am getting happens when you create a yearly event and dont include a end of recurring date.

**Comment by t1k3** [comment]
I will check it, again.

**Comment by t1k3** [comment]
@rmenner Please check it: https://github.com/t1k3/laravel-calendar-event/tree/fix/date-time-merge

**Comment by rmenner** [comment]
@t1k3 Yearly works great now. Thanks so much!
