### ISSUE TITLE
Issue with getMonthlyEvents method

### ISSUE THREAD

**Issue by newelement** [t1k3hu/laravel-calendar-event#9]
For some reason using the Carbon object when comparing the dates is not working. Wonder if this is a Laravel or Carbon change? I had to convert the carbon date object to string for it to work.

```   
private static function getMonthlyEvents(\DateTimeInterface $endOfRecurring): Collection
{
        $month = str_pad($endOfRecurring->month, 2, '0', STR_PAD_LEFT);
		
        return TemplateCalendarEvent
            ::where(function ($q) use ($month) {
                $q->where('is_recurring', 0)
                    ->whereMonth('start_datetime', $month);
            })
            ->orWhere(function ($q) use ($endOfRecurring) {
                $q->where('is_recurring', 1)
                    ->whereNull('end_of_recurring')
                    ->where('start_datetime', '<=', $endOfRecurring->toDateString());
            })
            ->orWhere(function ($q) use ($endOfRecurring) {
                $q->where('is_recurring', 1)
                    ->where('start_datetime', '<=', $endOfRecurring->toDateString())
                    ->whereMonth('end_of_recurring', '<=', $endOfRecurring->toDateString());
            })
            ->with('events')
            ->get();
}
```

**Comment by t1k3** [comment]
I will check on Sunday.
Thank you for the issue.

**Comment by t1k3** [comment]
I will migrate to Carbon 2, because 1 is deprecated.

**Comment by t1k3** [comment]
I don't have time this week, but I will fix it.

**Comment by newelement** [comment]
I'll try to help out if I can carve out some time as well.

**Comment by t1k3** [comment]
Oh, okay. Thank you for understanding.

- I checked it. The tests ran without fail. And it working to me. :/
- I upgraded to Carbon, testbench, phpunit - it is a difficult. So, I need some more time, but I will hurry.
- I fixed the code format in the original issue comment.

**Comment by t1k3** [comment]
- I upgraded Illuminate.
- Fixed tests with new versions.
- Fixed `getMonthlyEvents` method.

@newelement Please check it: https://github.com/t1k3/laravel-calendar-event/tree/bugfix/9

**Comment by newelement** [comment]
Thanks. I'll try to check tonight.

**Comment by newelement** [comment]
Works good for me
